import type { NextPage } from 'next';
import Head from 'next/head';

import { Layout } from '../components';
import { Review } from '../types';

type HomeProps = {
    reviews: Review[];
};

const Home: NextPage<HomeProps> = ({ reviews }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                {reviews.map((review) => (
                    <div key={review.createdAt + review.name}>{review.name}</div>
                ))}
            </Layout>
        </>
    );
};

export async function getServerSideProps(context) {
    //Ideally, we'd do the data fetching here rather than in the API route since we'd have fewer hops,
    //however due to persistance of review data, I'm needing to do it there.

    const data = await fetch(`${process.env.APPLICATION_URL}/api/reviews`);

    return {
        props: {
            reviews: await data.json(),
        },
    };
}

export default Home;
